### PR TITLE
add custom_llm_provider option for litellm 

### PR DESCRIPTION
**Pull request by kylehh**
### Describe the changes you have made:
1, Add custom_llm_provider which will be used for litellm for custom openai usage (like [Anyscale Endpoint](https://app.endpoints.anyscale.com/landing))
2, Fixed a bug in setup_text_llm which didn't remove the first message. 
### Reference any relevant issue (Fixes #000)

- [x ] I have performed a self-review of my code:

### I have tested the code on the following OS:
- [ ] Windows
- [x ] MacOS
- [ x] Linux

### AI Language Model (if applicable)
- [ ] GPT4
- [ x] GPT3
- [ x] Llama 7B
- [ ] Llama 13B
- [ ] Llama 34B
- [ ] Huggingface model (Please specify which one)

### CODE REVIEW

**Comment by KillianLucas** [comment]
I think this should work by setting `--api_base`? Or is this to change the format of the API call away from "openai" (I'm an OpenAI guy so sorry for my confusion!)

**Comment by kylehh** [comment]
Hi @KillianLucas yes, in order to work with other OpenAI API compatible endpoint services, we need to supply both api_base  and custome_llm_provider parameter, and this is due to the implementation of [LiteLLM](https://github.com/BerriAI/litellm/blob/ce62dc40b9f0d2662fb345a690ce14baaa4a45dd/litellm/main.py#L352). 

If you directly call openai.ChatCompletion.create API, then api_base is enough.

**Comment by KillianLucas** [comment]
Hey @kylehh we need better docs on this but it looks like we can skip this parameter [by letting folks pass it in before a "/" in the model name.](https://github.com/BerriAI/litellm/blob/ce62dc40b9f0d2662fb345a690ce14baaa4a45dd/litellm/main.py#L247)

So users should be able to put "custom_openai/" before the model name then set `api_base` to use it as an OpenAI compatible endpoint. Let me know if that works and I'll close this PR + update the docs, if not tho I'll merge it.

(tbh ideally we'd be able to put everything in the model string... i guess we can't because api_base needs to be set separately, but ideally we'd just have one magic string to identify each LLM. for now i think the best we can do is just having as few params as possible)

**Comment by kylehh** [comment]
Hi @KillianLucas Thanks for looking closely into this issue!  I tried your suggestion but unfortunately it's not working for now b/c anyscale is not in llm provider_list yet. I will make a PR to litellm to add it so it should work.
If so, I will remove the adding custom_llm_provider part of the PR and only leave the bug fix in setup_text_llm.py

**Comment by kylehh** [comment]
The changes should be made in litellm. And I will close this PR and open another for the bug fix
Thanks!

**Pull request closed without merging**
