### PR TITLE
Skip wrap_in_trap on Windows

### LINKED ISSUE #547: shell.py trying to trap in Windows
### Describe the bug

shell.py attempts to trap errors in Windows command prompt, but that only works in bash

### Reproduce

Create a request requiring command prompt execution

### Expected behavior

Command executes without "trap is not a valid command" error

### Screenshots

_No response_

### Open Interpreter version

0.1.6

### Python version

3.11.5

### Operating System name and version

Windows 11

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by goalkeepr**
### Reference any relevant issue (Fixes #547 )

- [X] I have performed a self-review of my code:

### I have tested the code on the following OS:
- [X] Windows
- [ ] MacOS
- [ ] Linux

### AI Language Model (if applicable)
- [X] GPT4
- [ ] GPT3
- [ ] Llama 7B
- [ ] Llama 13B
- [ ] Llama 34B
- [ ] Huggingface model (Please specify which one)

### CODE REVIEW

**Comment by KillianLucas** [comment]
Hi @goalkeepr, great catch-- I noticed a lot of people having this problem. Will push to `pip` in ~1 hour.

**Comment by tommymaher15** [comment]
Very curious to try this branch out tomorrow.  I'm really trying to find a branch where OI works for windows, so I can start reasoning up from there to figure out where we could be having issues with getting it running locally.

**Comment by goalkeepr** [comment]
Main branch works in Windows just fine for the most part!

**Comment by tommymaher15** [comment]
Oh didnt know that! 

I was trying to get it working myself maybe I was messing something up thats great news. 

I'll give it another bash in the morning had some weird issues with it  even running the pip-install. 

What versions are you using yourself?

**Comment by goalkeepr** [comment]
I just keep up with whatever the latest version is.

Check out this video, he does an install and walkthrough!
https://youtu.be/SqnXUHwIa3c

**Pull request merged**
