### PR TITLE
add Azure OpenAI support

### PR DESCRIPTION
**Pull request by ifsheldon**
As I proposed in https://github.com/KillianLucas/open-interpreter/issues/43, I added basic support for Azure OpenAI GPT4 and GPT3.5.

I tested it with my GPT4 deployment, as shown below.

img_v2_a1ff0d63-2186-4064-8b5f-506047385e2g

### CODE REVIEW

**Review by KillianLucas — APPROVED** [review]
Wow. This is _fantastic_! Incredible work @ifsheldon.

Merging now and will update the documentation.

**Comment by KillianLucas** [comment]
I think the build is failing because it's not using the repo secret (my OpenAI key). Will merge anyway lol (because then it will use the repo secrets to build it)

Any idea how to get around this?

**Comment by KillianLucas** [comment]
Hey, do these docs look okay? Also, u in [the discord?](https://discord.gg/YG7APUyJ5)

#### Azure Support

To connect to an Azure deployment, the `--use-azure` flag will walk you through setting this up:

```
interpreter --use-azure
```

In Python, set the following variables:

```
interpreter.use_azure = True
interpreter.api_key = "your_openai_api_key"
interpreter.azure_api_base = "your_azure_api_base"
interpreter.azure_api_version = "your_azure_api_version"
interpreter.azure_deployment_name = "your_azure_deployment_name"
```

**Comment by ifsheldon** [comment]
@KillianLucas 

> Any idea how to get around this?

Applying for Azure OpenAI as an individual seems not easy. I think a mock server can do, but it takes too much effort, considering Azure changes their APIs whenever they like :( 

> Hey, do these docs look okay? Also, u in [the discord?](https://discord.gg/YG7APUyJ5)

The doc looks great, thanks! I joined discord just now.

**Comment by TanmayDoesAI** [comment]
@ifsheldon could I get your discord username? can't seem to find you there, Thank you

**Comment by lewislovelock** [comment]
is it working yet? i use:
```
interpreter --use-azure
```
seems current interpreter package haven't update yet.
```
$ interpreter -h
usage: interpreter [-h] [-y] [-f] [-l] [-d]

Chat with Open Interpreter.

options:
  -h, --help   show this help message and exit
  -y, --yes    execute code without user confirmation
  -f, --fast   use gpt-3.5-turbo instead of gpt-4
  -l, --local  run fully local with code-llama
  -d, --debug  prints extra information
```
i already did:
```
pip install --upgrade open-interpreter
```
pip list the version :
```
open-interpreter   0.1.0
```

**Pull request merged**
