### PR TITLE
feat: add flag to specify max retries for API calls

### LINKED ISSUE #310: Add a flag to specify number of retries / exponential backoff
### Is your feature request related to a problem? Please describe.

Code Generation can get stuck in an infinite loop, which can indefinitely consume API credits  

### Describe the solution you'd like

 Would be great to be able to add an option to throttle / exponential backoff   

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by eden-chan**
Would like to better understand how to implement an opt-in throttling / exponential backoff feature for smoother error handling

Fixes #310

### CODE REVIEW

**Comment by codeacme17** [comment]
Hello @eden-chan ! Exposing the 'retry' count for user configuration is a good choice in my opinion. However, I feel that many users might not understand the meaning of the `max_retries` parameter. Could you perhaps enhance the comments for this parameter to make it more comprehensible?

**Comment by jordanbtucker** [comment]
In addition to @codeacme17's recommendations, can you also please rename the arg to `--max-retries`. Dashes in command line args are more common than underscores.

**Comment by ericrallen** [comment]
Hey there, @eden-chan!

This was a cool idea, and I’m sorry we didn’t get around to it when you first proposed it.

If you’re still interested in this Pull Request, I think we just need to adjust it a little bit based on the recent refactor of the codebase.

The retries are now in a variable here: https://github.com/KillianLucas/open-interpreter/blob/286228d324e81d18e8ef535df090bf3cf4236a0e/interpreter/code_interpreters/subprocess_code_interpreter.py#L59

And we can still use the basic `--max_retries` flag you set up (which will also be available able via the config file now, too), but just need to move that part to: https://github.com/KillianLucas/open-interpreter/blob/286228d324e81d18e8ef535df090bf3cf4236a0e/interpreter/cli/cli.py#L11

If you’d rather submit a new PR than resolve the merge conflicts and move the changes to the new file locations, just `@` mention me in the PR and we’ll get it reviewed and put into the merge queue.

**Comment by ericrallen** [comment]
I’m going to go ahead and  lose this one as stale and we’ll revisit it.

**Pull request closed without merging**
