### PR TITLE
add budget manager for api calls

### PR DESCRIPTION
**Pull request by krrishdholakia**
Addressing this issue https://github.com/KillianLucas/open-interpreter/issues/303

using LiteLLM's budget manager - https://docs.litellm.ai/docs/budget_manager, this PR creates a budget for a session (default set to $10). If this amount gets exceeded, it raises an Exception. 

Confirming it works locally: 
Screenshot 2023-09-12 at 10 21 55 PM

### CODE REVIEW

**Comment by WilliamEspegren** [comment]
Neat feature, well needed 👍

**Comment by krrishdholakia** [comment]
cc: @KillianLucas @jordanbtucker let me know if there's anything further required on my end

**Comment by jordanbtucker** [comment]
@krrishdholakia This is awesome! How does a user set their budget?

**Comment by krrishdholakia** [comment]
I didn't expose this as a user controllable setting in the initial PR, but that's a great idea. I'll make updates. 

Re: switch to local - yup sounds good, so check local -> if a model exists -> switch to that -> else raise exception?

**Comment by jordanbtucker** [comment]
I wouldn't even worry about checking if a model exists. Just take them to the local menu after explaining that they've reached their configured budget. And maybe let them know how to change that budget.

Lastly, I think we should remove the default budget and make this an opt-in feature. No budget by default, but they can configure one if they want.

**Comment by krrishdholakia** [comment]
Thanks for the feedback, let me make some changes and update this PR @jordanbtucker

**Comment by krrishdholakia** [comment]
Hey @jordanbtucker, 

Simplified the code based on yours + other feedback. 

Budget manager is now just: 
```
litellm.max_budget = max_budget # your max budget
```

You can set it by doing: 
```
interpreter --max_budget 0.001 # sets a budget of $0.01 
```

It raises a custom error: `litellm.BudgetExceededError`, that i have a try-except around. 

If true, i set `self.local=True`.

**Comment by krrishdholakia** [comment]
Need advice on the last part, as that throws an error due to the menu workflow being triggered at the start of the code interpreter process (before i pass in my openai api key). 

Is there a way for me to trigger this menu easily or do i need to refactor the code and make that into a separate function.

**Comment by jordanbtucker** [comment]
This is looking great! Just so I understand, is this a session-based budget? Like it resets every time the user restarts OI, or does it keep track between OI runs?

One more thing I thought of, it would be nice if users could set their default budget using an environment variable which can be overwritten by the `--budget` arg. Sorry for all the change requests.



> Is there a way for me to trigger this menu easily or do i need to refactor the code and make that into a separate function?

Probably needs to be refactored, but I can take a closer look if you need.

**Comment by krrishdholakia** [comment]
It's a session-based budget -> the module gets set with it when it's initialized. 

re: feedback - 
```
os.environ["LITELLM_MAX_BUDGET"] = 100 # sets the budget to $100
```

Would this be in line with what you were thinking?

**Comment by jordanbtucker** [comment]
That works! Eventually I plan to get away from environment variables for casual users and go with a config file and a CLI for managing the configuration.

**Comment by krrishdholakia** [comment]
oh - say more? @jordanbtucker what's the hypothetical code look like?

**Comment by krrishdholakia** [comment]
@jordanbtucker updated based on requests. 

Menu now works. 

It also checks os.getenv for LITELLM_MAX_BUDGET

**Comment by KillianLucas** [comment]
Incredible work @krrishdholakia. Lots of people's biggest issue with Open Interpreter is token cost. Excited to really highlight this feature soon and thank you + LiteLLM. Merging now.

**Pull request merged**
