### PR TITLE
Refactor: Add more types and check step in the pipeline

### PR DESCRIPTION
**Pull request by zya**
* Adding more type hints - Most of the codebase has types now. More can be done but this is a good base for the PR to be merged if folks are happy.
* Adding type check step to build pipeline

I personally think this step is a good prep for the refactor to begin. As there are not many tests, adding type hints before refactoring will help folks understand the code and refactor easier.

What do folks think?

### CODE REVIEW

**Comment by codeacme17** [comment]
@zya A great start!

**Comment by zya** [comment]
Added more tests and unit tests work fine too. @codeacme17 @KillianLucas 
Let me know your thoughts.

**Comment by codeacme17** [comment]
Hi @zya, I've read your changes, and I believe it's a great start for the refactoring project!

**Comment by codeacme17** [comment]
@zya, sry bro, I am currently just a contributor to this project and don't have merge permissions. You might want to wait for an administrator to handle the merge.

**Comment by zya** [comment]
> @zya, sry bro, I am currently just a contributor to this project and don't have merge permissions. You might want to wait for an administrator to handle the merge.

@KillianLucas ?

**Pull request closed without merging**
