### PR TITLE
Updated litellm and openai

### PR DESCRIPTION
**Pull request by Notnaton**
### Describe the changes you have made:
Updated LiteLLM and OpenAI
Needed to add a check if content is None.
Only tested with LM Studio

### Reference any relevant issue (Fixes #000)
https://github.com/KillianLucas/open-interpreter/issues/765
- [x] I have performed a self-review of my code:

### I have tested the code on the following OS:
- [x] Windows
- [ ] MacOS
- [ ] Linux

### AI Language Model (if applicable)
- [ ] GPT4
- [ ] GPT3
- [x] Llama 7B
- [ ] Llama 13B
- [ ] Llama 34B
- [ ] Huggingface model (Please specify which one)

### CODE REVIEW

**Comment by Notnaton** [comment]
This might fix this: https://github.com/KillianLucas/open-interpreter/compare/v0.1.15...v0.1.16#diff-759d9f02bb48ecd82e5b24e5725270c6932e76159967c46ee8742470424dce52

**Comment by Notnaton** [comment]
@CyanideByte thanks, I will check it out after work 👍

**Comment by Notnaton** [comment]
Excellent @catmeowjiao

**Comment by catmeowjiao** [comment]
I'm sorry, I've been very busy lately, so the pull request may be delayed. Please forgive me!

**Comment by vijaykramesh** [comment]
any update on this @Notnaton ?  I was looking into embedding open-interpreter as a griptape tool but the version conflicts make it difficult..

**Comment by Notnaton** [comment]
I'm going to look into it again, but it might be after xmas/new years. A lot of people are running into problems with outdated openai/litellm packages.

**Comment by vijaykramesh** [comment]
haha I thought I was going insane, I had just set a remote to your fork, was trying to checkout your branch, and suddenly it was gone.  Then I refreshed the UI and it also was 404!  Fast response 🥇 

No worries, look forward to checking back

**Pull request closed without merging**
