### PR TITLE
Add Weights and Biases Tracing

### LINKED ISSUE #123: Feature Request: ChatGPT Plus sub use
This project is wonderful! You're amazing!

I would like to put it on the back burner to consider enabling the use of GPT-4 through a ChatGPT+ subscription via headless chrome scrapping or something like that.

I realize this is a very different direction than API interaction, but it would be so lovely for cost reasons. :)

### PR DESCRIPTION
**Pull request by ash0ts**
### Changes made:
- Add Weights & Biases as an available option to store session history of messages with matching cli flag in handle save operations and exiting of program
- Optional import of wandb only triggered when appropriate cli flag is set
- Added logic and cli flag to automatically trigger save command after a certain interval of user interactions have occurred
- Added timestamp to the message history
- Added ending timestamp for user interactions
- Added logic to process the timestamps away before passing to llm endpoint

- [X] I have performed a self-review of my code:

### I have tested the code on the following OS:
- [ ] Windows
- [X] MacOS
- [X] Linux

### CODE REVIEW

**Comment by ash0ts** [comment]
This is an example of a workspace generated by tracing with the appropriate flag:

https://wandb.ai/a-sh0ts/open-interpreter/

**Comment by ishaan-jaff** [comment]
@ash0ts is this compatible with LiteLLM ? Open interpreter uses litellm https://github.com/BerriAI/litellm for completion calls. Will tracking completion calls work ?

**Comment by ash0ts** [comment]
Hey @ishaan-jaff! We are building out functionality to automatically capture completion calls similar to a monitoring dashboard, however that is a WIP. The instrumentation provided here moreso focuses on the better visualization and storage of the overall conversation with the LLM as opposed to raw communication of with the LLM.

This is a screenshot of our Traces tracing the conversation of the OI Agent
Screenshot 2023-09-16 at 11 29 49 AM

This is a screenshot of the Monitoring Dashboard we are building out
prodmon_mini_overview-ca58ed1ae5fd53137b009cfba0cf4721

Let me know if this isn't clear!

**Comment by ericrallen** [comment]
I’m going to go ahead and  lose this one as stale and we’ll revisit it.

**Pull request closed without merging**
