### PR TITLE
ui: optimize welcome message

### PR DESCRIPTION
**Pull request by codeacme17**
optimize welcome message, and extract the welcome message into the `_print_welcome_message` function

屏幕截图 2023-09-11 115144

### CODE REVIEW

**Comment by jordanbtucker** [comment]
The logo is a nice touch!

**Comment by codeacme17** [comment]
> The logo is a nice touch!

I really like the logo of this project!

**Comment by KillianLucas** [comment]
Wow, that is CLEAN. **I love it.** I didn't know that was a character that worked in the terminal!

Thanks @codeacme17, merging now.

**Review by noa062921 — CHANGES_REQUESTED** [review]
Leave

**Pull request merged**
