### PR TITLE
Add models to pull request template

### PR DESCRIPTION
**Pull request by mak448a**
### Describe the changes you have made:
I added AI language models to the pull request template.

- [x] I have performed a self-review of my code:

### I have tested the code on the following OS:
- [ ] Windows
- [ ] MacOS
- [x] Linux

### CODE REVIEW

**Comment by TanmayDoesAI** [comment]
@mak448a maybe just add an option where it is some other open source model, rest looks good to me!

**Comment by mak448a** [comment]
Oh wait sorry I get it

**Comment by mak448a** [comment]
@TanmayDoesAI What other models are available in this project?

**Comment by TanmayDoesAI** [comment]
@mak448a have a look at [running open interpreter locally](https://github.com/KillianLucas/open-interpreter#running-open-interpreter-locally) we could have most models running from huggingface, so if there's that user could choose that by choosing an option like `hf-model`.

**Comment by TanmayDoesAI** [comment]
LGTM thank you!

**Pull request merged**
