### PR TITLE
Added azure api version patch

### PR DESCRIPTION
**Pull request by hargunmujral**
### Describe the changes you have made:

- Azure openai uses an "api version" parameter when running open interpreter. Thus, added this as a param in the setup file
- Fixed broken link to CONTRIBUTING.md in the README.md

### Reference any relevant issue (Fixes #000)

- [ ] I have performed a self-review of my code:

### I have tested the code on the following OS:
- [ ] Windows
- [ ] MacOS
- [ ] Linux

### AI Language Model (if applicable)
- [ ] GPT4
- [ ] GPT3
- [ ] Llama 7B
- [ ] Llama 13B
- [ ] Llama 34B
- [ ] Huggingface model (Please specify which one)

### CODE REVIEW

**Comment by Notnaton** [comment]
Should this have a --api_version cli argument?

**Comment by KillianLucas** [comment]
Nice @hargunmujral. We should start moving in this direction of exposing more params via the Python package (and via CLI flags as @Notnaton mentioned, which I'll do after merging). Especially with the new `config` setup that @Notnaton is building, I think this takes us in the right direction. Merging!

**Comment by KillianLucas** [comment]
Also great catch on the `CONTRIBUTING` link!

**Comment by symonh** [comment]
Thanks everyone. I updated interpreter (`pip install...`) and then `export AZURE_API_VERSION=2023-08-01-preview`. Now when I run interpreter I get this error:

```
APIError(status_code=500, message=str(original_exception), llm_provider=custom_llm_provider, model=model)
litellm.exceptions.APIError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/',..)` Learn more: https://docs.litellm.ai/docs/providers
```

Following the litellm docs, I tried  running `interpreter --model=azure/nameai-63k-tpm`

This loads open interpreter, but when I pass a message to it I get 

`openai.error.InvalidRequestError: Invalid URL (POST /v1/openai/deployments/nameai-63k-tpm/chat/completions)`

My config looks like this:

```
local: false
temperature: 1
context_window: 31000
max_tokens: 3000
OPENAI_API_KEY: 97-*******************84
API_BASE: https://nameai.openai.azure.com/
API_TYPE: azure
MODEL: azure/nameai-63k-tpm
AZURE_API_VERSION: 2023-08-01-preview
```

I've played with setting API_BASE to https://nameai.openai.azure.com/openai/deployments/nameai-63k-tpm — but I get the same `openai.error.InvalidRequestError: Invalid URL (POST /v1/openai/deployments/nameai-63k-tpm/chat/completions)`.

Thank you for this project and for any help you can provide — this will be an **absolute dream** when I get it working!

**Comment by Notnaton** [comment]
@symonh use lower case in the config file and try again

**Comment by symonh** [comment]
@Notnaton Thank you very much — it's working! 

When analyzing data, how good should I expect the performance to be compared to ChatGPT? Roughly on par, minus the limitations from packages and compute, or less capable?

I just asked it to reshape a dataset and it performed beautifully :)

**Pull request merged**
