### PR TITLE
feat: add hints to Azure model

### PR DESCRIPTION
**Pull request by codeacme17**
Hi, I don't think Azure is necessarily using the GPT-4 model or GPT-3.5-turbo, so I added a separate model hint for Azure. For making it more friendly

Model: `Azure(deployment-name)`

Screenshot 2023-09-10 at 18 21 17

### CODE REVIEW

**Comment by KillianLucas** [comment]
Great commit @codeacme17! I can totally see why that would be confusing. Perfect fix, merging now.

**Comment by codeacme17** [comment]
> Great commit @codeacme17! I can totally see why that would be confusing. Perfect fix, merging now.

Thanks also for the great project! I will focus on this project and may submit multiple PRs in the near future 🚀

**Comment by codeacme17** [comment]
@KillianLucas It seems that something went wrong during the merge

**Comment by codeacme17** [comment]
@KillianLucas, I think my fork branch is not merged into your main branch. I'm not sure why this is happening. I want to provide some more PRs today and I don't know if you can finish this PR. 🙂 Otherwise my subsequent PR may affect your main branch. Waiting for your reply~

**Pull request merged**
