### PR TITLE
feat: add semgrep code scanning and guarddog for package installations

### PR DESCRIPTION
**Pull request by ericrallen**
This PR introduces some tools to help verify that code _might_ be safe to execute.

It adds a `--scan` flag that can be used to enable code scanning via [semgrep](https://semgrep.dev/) and a `--guarddog` flag that can be used to enable scanning [PyPI](https://github.com/DataDog/guarddog#pypi) and [npm](https://github.com/DataDog/guarddog#npm) packages with [guarddog](https://github.com/datadog/guarddog) before installing them.

`--scan` has 3 possible values: `auto` (always scan code with semgrep before asking to execute), `ask` (ask the user if they want to scan a code snippet before asking to execute), and `off` (don't ask to scan code).

Both the `--scan` and `--guarddog` options are disabled by default and are entirely opt-in.

This is a super interesting project, and while I know this won't make it 100% safe to execute Open Interpreter code, I hope it can start to provide some extra assurance and help mitigate some common threats.

Once [datadog/guarddog #249](https://github.com/DataDog/guarddog/issues/249) is resolved we can make some slight adjustments and include `guarddog` in the `pyproject.toml` dependencies, but for now the version of semgrep that it is pinned at has issues with scanning individual files like this with the automatic configuration based on [returntocorp/semgrep-rules #2894](https://github.com/returntocorp/semgrep-rules/issues/2894)

Just as a note, I was actually impressed that while testing some vulnerable files that _should_ trigger semgrep's rules Open Interpreter tried to save me from myself:

>  I'm sorry, but executing this code is not safe. The code contains potentially harmful operations, such as reading the /etc/passwd file, which contains sensitive system information. It's important to only execute code when you're sure it's safe and understand what it does.
> 
> If you need to test this code, I recommend doing so in a controlled environment, such as a virtual machine or a container, where it can't cause harm to your actual system.

I had to let it know that I was working on a code scanning implementation for Open Interpreter and needed it to try to execute this kind of code for testing purposes.

### CODE REVIEW

**Comment by ericrallen** [comment]
Here are some screenshots of these flags in action:

`--scan`:
Screen Shot 2023-09-01 at 11 10 25 PM

`--guarddog`:
Screen Shot 2023-09-01 at 4 26 36 PM

**Review by QosmosTheQ — APPROVED** [review]

**Comment by ericrallen** [comment]
Sorry I haven’t rebased and resolved the conflict yet. Once I’m back from vacation and have access to my laptop again, I’ll get it fixed up.

**Comment by ericrallen** [comment]
@KillianLucas I've resolved the conflicts and rebased to make sure the latest updates are all picked up.

**Comment by ericrallen** [comment]
Closing this in favor of #484 which adds semgrep via `--scan` and another PR to follow that will add `guarddog` functionality.

**Pull request closed without merging**
