### PR TITLE
fix all non-code typo error

### PR DESCRIPTION
**Pull request by YUFEIFUT**
### Describe the changes you have made:
I fix all non-code typo error that I have found in this project
### Reference any relevant issue (none)

- [x] I have performed a self-review of my code:

### I have tested the code on the following OS:
- [x] Windows
- [x] MacOS
- [x] Linux

### CODE REVIEW

**Comment by YUFEIFUT** [comment]
hey, buddy, what's wrong about this?
image
I have just fix some typo problems for this project, do I have to provide a API-KEY to solve this problem?

**Comment by sudhamjayanthi** [comment]
No, it's the problem with test — mostly likely the OpenAI API key was not setup properly for the tests.

**Comment by YUFEIFUT** [comment]
So what should I do next? anyone can help?

**Comment by YUFEIFUT** [comment]
@KillianLucas May I ask what the issue is and how can I fix it?

**Review by tomviner — APPROVED** [review]

**Comment by ericrallen** [comment]
Hey there, @YUFEIFUT!

I'm going to close this as stale for now, but if you want to fix the remaining typos in the comments, feel encouraged to reopen this with the changes in the newly refactored codebase, or open a new PR and we'll get it merged in.

**Pull request closed without merging**
